title: Welcome
description: > # this means to ignore newlines until "baseurl:"
  I am Munim Hasan Wasi.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Munim Hasan Wasi # add your name
author-img: mhw.png # add your photo
about-author: I am an undergraduate student at KAIST double majoring in Mathematics and Computer Science # add description
social-twitter: HBK__Wasi # add your Twitter handle
social-facebook: HBKWasi # add your Facebook handle
social-github: HBKWasi # add your Github handle
social-linkedin: hbk-wasi # add your Linkedin handle
social-email: wasi19524@gmail.com # add your Email address

# Disqus
discus-identifier: hbkwasi # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
